apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 1h
  timeout: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
  serviceAccountName: gotk-reconciler
  chart:
    spec:
      chart: redis
      version: 17.11.3
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: redis
  values:
    image:
      registry: docker.io
      repository: bitnamilegacy/redis   # <-- ensure this repo actually exists
      tag: 7.2.4-debian-12-r9         # <-- ensure this tag actually exists
      pullPolicy: IfNotPresent
    master:  
      podSecurityContext:
        enabled: true
        runAsNonRoot: true
        runAsUser: 5000 
        runAsGroup: 5000
        fsGroup: 5000  


      
  #    podSecurityContext:
  #     enabled: true
  #     runAsNonRoot: true
  #     runAsUser: 5000 
  #     runAsGroup: 5000
  #     fsGroup: 5000


    
