---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-network-01
spec:
  selector:
    matchLabels:
      app: cloudflared-network-01
  replicas: 3 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: cloudflared-network-01
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2023.10.0
        args:
        - tunnel
        # Points cloudflared to the config file, which configures what
        # cloudflared will actually do. This file is created by a ConfigMap
        # below.
        - --loglevel
        - info
        - --transport-loglevel
        - debug
        - --protocol
        - quic
        - --no-autoupdate
        - --metrics
        - 0.0.0.0:2000
        - --logfile
        - /proc/self/fd/1
        - run
        - --token
        - $(TOKEN)
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-tunnel-token
              key: value
        livenessProbe:
          httpGet:
            # Cloudflared has a /ready endpoint which returns 200 if and only if
            # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
