apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 1h
  timeout: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
  serviceAccountName: gotk-reconciler
  chart:
    spec:
      chart: external-dns
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  values:
    provider:
      name: cloudflare
    extraArgs:
      - --cloudflare-proxied
    sources:
      - ingress
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-token
            key: token
    podSecurityContext:
      runAsUser: 5000
      runAsGroup: 5000
      fsGroup: 5000
    securityContext:
      runAsUser: 5000
      runAsGroup: 5000
       
