apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  timeout: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
  serviceAccountName: gotk-reconciler
  chart:
    spec:
      chart: cert-manager
      version: ~1.12.3
      sourceRef:
        kind: HelmRepository
        name: jetstack-helm-charts
        namespace: cert-manager
  values:
    installCRDs: true
    # securityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1001
    #   runAsGroup: 1001
    #   fsGroup: 1001
    #   seccompProfile:
    #     type: RuntimeDefault

    # containerSecurityContext:
    #   runAsNonRoot: true
    #   allowPrivilegeEscalation: false
    #   readOnlyRootFilesystem: true
    #   capabilities:
    #     drop:
    #       - ALL
    # webhook:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1001
    #     runAsGroup: 1001
    #     fsGroup: 1001
    #     seccompProfile:
    #       type: RuntimeDefault

    #   containerSecurityContext:
    #     runAsNonRoot: true
    #     allowPrivilegeEscalation: false
    #     readOnlyRootFilesystem: true
    #     capabilities:
    #       drop:
    #         - ALL
    # cainjector:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1001
    #     runAsGroup: 1001
    #     fsGroup: 1001
    #     seccompProfile:
    #       type: RuntimeDefault        
    #   containerSecurityContext:
    #     runAsNonRoot: true
    #     allowPrivilegeEscalation: false
    #     readOnlyRootFilesystem: true
    #     capabilities:
    #       drop:
    #         - ALL

    securityContext:
    #   runAsNonRoot: true
      runAsUser: 5000
      runAsGroup: 5000
      fsGroup: 5000
      # seccompProfile:
      #   type: RuntimeDefault

    containerSecurityContext:
      # runAsNonRoot: true
      runAsUser: 5000
      runAsGroup: 5000
      # allowPrivilegeEscalation: false
      # readOnlyRootFilesystem: true
      # capabilities:
      #   drop:
      #     - ALL
    webhook:
      securityContext:
        # runAsNonRoot: true
        runAsUser: 5000 
        runAsGroup: 5000
        fsGroup: 5000
        # seccompProfile:
        #   type: RuntimeDefault

      containerSecurityContext:
        # runAsNonRoot: true
        runAsUser: 5000
        runAsGroup: 5000
        # allowPrivilegeEscalation: false
        # readOnlyRootFilesystem: true
        # capabilities:
        #   drop:
        #     - ALL
    cainjector:
      securityContext:
        # runAsNonRoot: true
        runAsUser: 5000
        runAsGroup: 5000
        fsGroup: 5000
        # seccompProfile:
        #   type: RuntimeDefault        
      containerSecurityContext:
        # runAsNonRoot: true
        runAsUser: 5000
        runAsGroup: 5000
        # allowPrivilegeEscalation: false
        # readOnlyRootFilesystem: true
        # capabilities:
        #   drop:
        #     - ALL