---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
spec:
  interval: 5m
  serviceAccountName: gotk-reconciler
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: ~0.9.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts-helm-charts
        namespace: github-arc-system
  values:
    metrics:
      controllerManagerAddr: ":8080"
      listenerAddr: ":8080"
      listenerEndpoint: "/metrics"
  upgrade:
    remediation:
      remediateLastFailure: true
