# apiVersion: spv.no/v2beta1  # needed to pull gha-runner-scale-set-controller from ghcr.io
# kind: AzureKeyVaultSecret
# metadata:
#   name: ghcr-image-pull-secret
# spec:
#   vault:
#     name: empcentral-dv-kv
#     object:
#       name: ghcr-image-pull-secret
#       type: secret
#   output:
#     secret: 
#       name: ghcr-image-pull-secret
#       type: kubernetes.io/dockerconfigjson
