apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  timeout: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
  serviceAccountName: gotk-reconciler
  chart:
    spec:
      chart: ingress-nginx
      version: "^4.7.x"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  values:
    controller:
      resources:
        requests:
          memory: 1G
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 11
        targetMemoryUtilizationPercentage: 60
      service:
        external:
          enabled: false
        internal:
          enabled: true
          # create internal LB
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      config:
        proxy-body-size: 10m
        proxy-buffer-size: 16k
        large-client-header-buffers: "4 64k"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: ingress-nginx
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: ingress-nginx
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 5000    
        runAsGroup: 5000
        fsGroup: 5000
      # containerSecurityContext:
      #   runAsNonRoot: true
      #   runAsUser: 5000
      #   runAsGroup: 5000
      #   allowPrivilegeEscalation: false
      #   seccompProfile:
      #     type: RuntimeDefault
      #   readOnlyRootFilesystem: false  